# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f252cfde9c3c1cd7134ac9bd9850801539b72d36d9dca7348f7d86cfedab53234276808338ede9b2e09d24ee6c09b759a510a6b65be2a77ceea03027081d3eb

test:
  secret_key_base: e7429254b84070e1fccae02225ecc256d538b1cd50689d16df7cbba314133bcbb796c546c73ffe7aebe752e5e558df61aedec2386de8dbce46b618f886b6c3cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
